# Project information
site_name: 'Ingot Documentation'
site_description: 'A GUI toolkit for ROBLOX'
site_author: 'MemoryPenguin'
site_url: 'https://memorypenguin.github.io/RbxIngot'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/MemoryPenguin/RbxIngot'

# Directory and theme
docs_dir: 'Source'
site_dir: 'Output'
theme: 'material'

# Pages
pages:
  - Home: 'index.md'
  - Using Components: 'using.md'
  - Components:
    - 'Dropdown': 'components/dropdown.md'
  - Support Modules:
    - UDim4: 'support/udim4.md'
  - Making Components: 'making.md'

# Options
extra:
  version: '0.1.0'
  palette:
    primary: 'blue grey'
    accent: 'lime'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'MemoryPenguin'
    twitter: 'MemoryPenguin'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'